'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DataGridBackground.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private _WindowLayout As String

        Private Shared defaultInstance As DataGridBackground.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DataGridBackground.Properties.Settings())), DataGridBackground.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return DataGridBackground.Properties.Settings.defaultInstance
            End Get
        End Property

        Public Property WindowLayout As String
            Get
                Return _WindowLayout
            End Get

            Friend Set(ByVal value As String)
                _WindowLayout = value
            End Set
        End Property
    End Class
End Namespace
